language: java
jdk: openjdk11

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2

#services:
#  - docker
#
#script:
#  - mvn package -Pnative -Dquarkus.native.container-build=true