= excel2adoc CLI

image:https://travis-ci.com/ncomet/excel2adoc.svg?branch=master["excel2adoc build", link="https://travis-ci.com/ncomet/excel2adoc"] image:https://codecov.io/gh/ncomet/excel2adoc/branch/master/graph/badge.svg["excel2adoc coverage", link="https://codecov.io/gh/ncomet/excel2adoc"]

== User guide

`$ excel2adoc -h`

[code, bash]
----
Usage: excel2adoc [-hntV] [-s=2] <inputFiles>...
Prints .xlsx or .csv file(s) into their asciidoc representation on stdout
      <inputFiles>...   One or more .xlsx or .csv file(s) to print to stdout
  -h, --help            Show this help message and exit.
  -n, --no-headers      Disables interpretation of first row as header
                          Default: false
  -s, --sheet=2         Sheet number, starting at 1. if not provided, it will
                          try to print all sheets for all files
  -t, --no-titles       Disables table title using file name and sheet name (or
                          just file name for .csv)
                          Default: false
  -V, --version         Print version information and exit.
----

== Why?

Because we all know product managers, project managers, timetable reporters that only swear by _Excel_ to provide us with some insightful piece of information.

Let's get real: if we want it to work, we use https://www.oreilly.com/library/view/living-documentation-continuous/9780134689418/[documentation as code,window=_blank], not binaries.

Here is a CLI tool to convert to the real deal, *text*. Just text, that will find all its use under a proper CVS.

== How does it work?

This project uses Quarkus, the Supersonic Subatomic Framework, https://poi.apache.org/[Apache POI] and https://kotlinlang.org/[Kotlin]

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/[window=_blank]

== Running the application in dev mode

You can run your application in dev mode that enables live coding using:

[source,shell script]
----
./mvnw compile quarkus:dev

----

== Packaging and running the application

The application can be packaged using:

[source,shell script]
----
./mvnw package
----

It produces the `excel2adoc-1.0-runner.jar` file in the `/target` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/lib` directory.

If you want to build an _über-jar_, execute the following command:

[source,shell script]
----
./mvnw package -Dquarkus.package.type=uber-jar
----

The application is now runnable using `java -jar target/excel2adoc-1.0-runner.jar`.

== Creating a native executable

You can create a native executable using: 

[source,shell script]
----
./mvnw package -Pnative
----

Or, if you don't have GraalVM installed, you can run the native executable build in a container using: 

[source,shell script]
----
./mvnw package -Pnative -Dquarkus.native.container-build=true
----

You can then execute your native executable with: `./target/excel2adoc-1.0-runner`

If you want to learn more about building native executables, please consult https://quarkus.io/guides/maven-tooling.html[window=_blank]
