name: release-build-native-win64

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@latest
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '20.2.0.java11'
    - name: Install native-image
      run: |
        %JAVA_HOME%/bin/gu.cmd install native-image
      shell: cmd
    - name: Configure Pagefile
      # Increased the page-file size due to memory-consumption of native-image command
      # For details see https://github.com/actions/virtual-environments/issues/785
      uses: al-cheb/configure-pagefile-action@v1.2
    - name: Set version
      run: mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
      shell: cmd
    - name: Build native executable
      # Invoke the native-image build with the necessary Visual Studio tooling/environment intialized
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
        mvnw package -Dnative"
      shell: cmd
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/excel2adoc-${{ github.event.release.tag_name }}-runner.exe
        asset_name: excel2adoc-${{ github.event.release.tag_name }}-win64.exe
        asset_label: win64
        asset_content_type: application/octet-stream