name: release-build-native-macos

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.2.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Set version
      run: ./mvnw versions:set -DnewVersion="${{ github.event.release.tag_name }}"
    - name: Build native executable
      run: ./mvnw package -Dnative
    - name: Upload native executable
      id: upload-native-image-macos
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/excel2adoc-${{ github.event.release.tag_name }}-runner
        asset_name: excel2adoc-${{ github.event.release.tag_name }}-macos
        asset_label: macos
        asset_content_type: application/octet-stream